version: '2'

services:
  ghost_data:
    image: tianon/true
    volumes:
      - /var/lib/ghost
  ghost_backup_data:
    image: tianon/true
    volumes:
      - /backups
  app:
    image: gordonchan/ghost-mailgun
    volumes_from:
      - ghost_data
    restart: unless-stopped
  server:
    image: gordonchan/nginx-ghost
    links:
      - app:ghost
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  ghost_backup:
    image: bennetimo/ghost-backup
    volumes_from:
      - ghost_data
      - ghost_backup_data